### ISSUE TITLE
Add support for tab delimiter

### ISSUE THREAD

**Issue by yomajo** [maroofi/csvtool#2] opened 2023-06-12 20:01 UTC
Trying to read file:
```
>>head -1 test25.txt 
>>order-id	order-item-id	purchase-date	payments-date	buyer-email...
```

`>>csvtool -c 2 -d '\t' --encoding utf-8 test25.txt`
raises error:

```
>>Traceback (most recent call last):
  File "/home/devyo/.local/bin/csvtool", line 8, in <module>
    sys.exit(main())
  File "/home/devyo/.local/lib/python3.10/site-packages/csvtool/csvtool.py", line 144, in main
    reader = csv.reader(fr,quotechar='"',delimiter=pargs.delimiter,quoting=csv.QUOTE_ALL,skipinitialspace=True)
TypeError: "delimiter" must be a 1-character string
```

Will not provide additional feedback, close issue if when solved. Good luck!

**Comment by maroofi** [comment] 2023-06-13 10:09
Hi yomajo,
Thanks again for the feedback.
the problem is not related to the code but the way you insert tab character in your command line.

to insert tab character in your bash, use one of the following approaches:
1. Using $ sign like this: `csvtool.py -d$'\t' -t tab.csv`
2. or press ctrl+v and then type tab inside the quote like this: `csvtool.py -d'        ' -t tab.csv`

I'm gonna close it since it's not relevant.
Thanks again.

**Closed as completed by maroofi** 2023-06-13 10:09 UTC
